# Generated by Django 3.2.7 on 2021-11-17 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20211117_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='duration',
            new_name='question_duration',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='duration',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='score',
            new_name='quiz_duration',
        ),
    ]
