# Generated by Django 3.2.7 on 2021-10-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=225)),
                ('topic', models.CharField(max_length=225)),
                ('level', models.PositiveIntegerField()),
                ('notes', models.FileField(upload_to='work/%Y/%m/%d/')),
                ('term', models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'threee')], max_length=225)),
            ],
        ),
    ]
