# Generated by Django 3.2.7 on 2021-10-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worknotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='level_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='notes',
            name='level',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='notes',
            name='term',
            field=models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three')], max_length=5),
        ),
    ]
