# Generated by Django 3.2.7 on 2021-11-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worknotes', '0003_alter_notes_level_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
