# Generated by Django 3.2.7 on 2022-01-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worknotes', '0004_notes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='level',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='notes',
            name='term',
            field=models.CharField(choices=[('All', 'All'), ('One', 'One'), ('Two', 'Two'), ('Three', 'Three')], max_length=5),
        ),
    ]
