# Generated by Django 3.2.7 on 2022-01-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worknotes', '0005_auto_20220106_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='level',
            field=models.CharField(choices=[('Primary', 'P'), ('Secondary', 'S')], default='', max_length=9),
        ),
    ]
