# Generated by Django 3.2.7 on 2022-04-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worknotes', '0010_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='level',
            field=models.CharField(default='', max_length=225),
        ),
    ]
