# Generated by Django 3.2.7 on 2021-11-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211028_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level_number',
            field=models.PositiveIntegerField(default=1, verbose_name='class'),
        ),
    ]
